// 스태프 이름을 한국어로 번역하는 함수
const translateStaffName = (staffName) => {
  const translations = {
    "Eiichirou Oda": "오다 에이이치로",
    "Junji Shimizu": "시미즈 준지",
    "Takashi Ootsuka": "오오츠카 타카시",
    "Katsumi Tokoro": "토코로 카츠미",
    "Kounosuke Uda": "우다 코우노스케",
    "Kazuhisa Takenouchi": "타케노우치 카즈히사",
    "Takahiro Imamuro": "이마무로 타카히로",
    "Tatsuya Nagamine": "나가미네 타츠야",
    "Gorou Taniguchi": "타니구치 고로",
    "Hiroaki Miyamoto": "미야모토 히로아키",
    // 추가 번역 데이터
  };

  return translations[staffName] || staffName;
};

// 스태프 역할을 한국어로 번역하는 함수
const translateStaffRole = (role) => {
  const roles = {
    director: "감독",
    origin: "원작",
  };

  return roles[role] || "Unknown";
};

// 장르 이름을 한글로 번역하는 매핑
// prettier-ignore
const genreTranslations = {
  "Action": "액션",
  "Adventure": "모험",
  "Comedy": "코미디",
  "Drama": "드라마",
  "Ecchi": "성인",
  "Fantasy": "판타지",
  "Horror": "공포",
  "Mahou Shoujo": "마법소녀",
  "Mecha": "메카",
  "Music": "음악",
  "Mystery": "미스터리",
  "Psychological": "추리",
  "Romance": "로맨스",
  "Sci-Fi": "SF",
  "Slice of Life": "일상",
  "Sports": "스포츠",
  "Supernatural": "초자연적인",
  "Thriller": "스릴러",
};

// 장르를 한글로 번역하는 함수
const translateGenre = (genres) => {
  const translatedGenres = genres
    .map((genre) => genreTranslations[genre] || genre) // 매핑된 번역이 없으면 원래 이름 사용
    .sort((a, b) => a.localeCompare(b, "ko-KR")); // 가나다순 정렬
  return translatedGenres;
};

// 태그 이름을 한글로 번역하는 매핑
// prettier-ignore
const tagTranslations = {
  '4-koma': '4컷 만화',
  "Achromatic": "무채색",
  'Achronological Order': '순서가 변함',
  'Acrobatics': '곡예',
  "Acting": "연기",
  'Adoption': '입양',
  'Advertisement': '광고',
  'Afterlife': '환생',
  'Age Gap': '나이 차이',
  'Age Regression': '회춘',
  'Agender': '무성',
  'Agriculture': '농업',
  'Airsoft': '서바이벌 게임 (에어소프트)',
  'Alchemy': '연금술',
  'Aliens': '외계인',
  'Alternate Universe': '평행 세계',
  'American Football': '미식축구',
  'Amnesia': '기억 상실',
  "Amputation": "절단",
  'Anachronism': '시대착오',
  'Ancient China': '고대 중국',
  'Angels': '천사',
  'Animals': '동물',
  'Anthology': '작품집',
  'Anthropomorphism': '의인화',
  'Anti-Hero': '안티히어로',
  'Archery': '활쏘기',
  'Aromantic': '무로맨틱',
  'Arranged Marriage': '정략 결혼',
  'Artificial Intelligence': '인공지능',
  'Asexual': '무성애',
  'Assassins': '암살자',
  'Astronomy': '천문학',
  'Athletics': '운동',
  'Augmented Reality': '증강 현실',
  'Autobiographical': '자서전적',
  'Aviation': '항공',
  'Badminton': '배드민턴',
  'Band': '밴드',
  'Bar': '바',
  'Baseball': '야구',
  'Basketball': '농구',
  'Battle Royale': '배틀 로얄',
  'Biographical': '전기적',
  'Bisexual': '양성애',
  "Blackmail": "약탈",
  'Board Game': '보드 게임',
  'Boarding School': '기숙 학교',
  'Body Horror': '신체 변형',
  'Body Swapping': '몸 바꾸기',
  'Bowling': '볼링',
  'Boxing': '권투',
  "Boys' Love": 'BL',
  'Bullying': '괴롭힘',
  'Butler': '집사',
  'CGI': '3D',
  'Calligraphy': '서예',
  'Cannibalism': '식인',
  'Card Battle': '카드 배틀',
  'Cars': '자동차',
  'Centaur': '켄타우로스',
  'Cheerleading': '치어리딩',
  'Chibi': '귀여운 아이',
  'Chimera': '키메라',
  'Chuunibyou': '중2병',
  'Circus': '서커스',
  'Class Struggle': '계급 투쟁',
  'Classic Literature': '고전 문학',
  'Classical Music': '고전 음악',
  'Clone': '클론',
  'Coastal': '해안가',
  'College': '대학교',
  'Coming of Age': '성장',
  'Conspiracy': '음모',
  'Cosmic Horror': '방대한 공포 ',
  'Cosplay': '코스프레',
  'Cowboys': '카우보이',
  'Crime': '범죄',
  'Criminal Organization': '범죄 조직',
  'Crossdressing': '여장남장',
  'Crossover': '크로스오버',
  'Cult': '사교도',
  'Cultivation': '수련,수행',
  'Cute Boys Doing Cute Things': '귀여운 남자아이들',
  'Cute Girls Doing Cute Things': '귀여운 여자아이들',
  'Cyberpunk': '사이버펑크',
  'Cyborg': '사이보그',
  'Cycling': '자전거',
  'Dancing': '춤',
  'Death Game': '데스게임',
  'Delinquents': '불량배',
  'Demons': '악마',
  'Denpa': '전파계',
  'Desert': '사막',
  'Detective': '탐정',
  'Dinosaurs': '공룡',
  'Disability': '장애',
  'Dissociative Identities': '다중인격',
  'Dragons': '용',
  'Drawing': '그림',
  'Drugs': '약물',
  'Dullahan': '두라한',
  'Dungeon': '던전',
  'Dystopian': '디스토피아',
  'E-Sports': 'e-스포츠',
  'Eco-Horror': '생태 공포',
  'Economics': '경제',
  'Educational': '교육',
  'Elderly Protagonist': '노인 주인공',
  'Elf': '엘프',
  'Ensemble Cast': '앙상블 캐스트',
  'Environmental': '환경',
  'Episodic': '에피소드',
  'Ero Guro': '에로 구로',
  'Espionage': '첩보',
  'Estranged Family': '서먹한 가족',
  'Fairy': '요정',
  'Fairy Tale': '동화',
  'Fake Relationship': '가짜 연애',
  'Family Life': '가족 생활',
  'Fashion': '패션',
  'Female Harem': '여성 하렘',
  'Female Protagonist': '여성 주인공',
  'Femboy': '여장남자',
  'Fencing': '펜싱',
  'Filmmaking': '영화 제작',
  'Firefighters': '소방관',
  'Fishing': '낚시',
  'Fitness': '피트니스',
  'Flash': '번개',
  'Food': '음식',
  'Football': '축구',
  'Foreign': '외국',
  'Found Family': '비혈연 가족',
  'Fugitive': '도망자',
  'Full CGI': '전체 3D',
  'Full Color': '전체 컬러',
  'Gambling': '도박',
  'Gangs': '갱단',
  'Gender Bending': '젠더 벤딩',
  'Ghost': '유령',
  'Go': '바둑',
  'Goblin': '고블린',
  'Gods': '신',
  'Golf': '골프',
  'Gore': '고어물',
  'Guns': '총',
  'Gyaru': '갸루',
  'Handball': '핸드볼',
  'Henshin': '변신',
  'Heterosexual': '이성애자',
  'Hikikomori': '히키코모리',
  'Hip-hop Music': '힙합 음악',
  'Historical': '역사',
  'Homeless': '노숙자',
  'Horticulture': '원예',
  'Ice Skating': '피겨 스케이팅',
  'Idol': '아이돌',
  'Inn': '여관',
  'Isekai': '이세계',
  'Iyashikei': '힐링물',
  'Jazz Music': '재즈 음악',
  'Josei': '여성',
  'Judo': '유도',
  'Kaiju': '괴수',
  'Karuta': '카루타',
  'Kemonomimi': '동물 귀',
  'Kids': '어린이',
  'Kingdom Management': '왕국 경영',
  'Konbini': '편의점',
  'Kuudere': '쿨데레',
  'LGBTQ+ Themes': 'LGBTQ+ 테마',
  'Lacrosse': '라크로스',
  'Language Barrier': '언어 장벽',
  'Lost Civilization': '잃어버린 문명',
  'Love Triangle': '삼각관계',
  'Mafia': '마피아',
  'Magic': '마법',
  'Mahjong': '마작',
  'Maids': '메이드',
  'Makeup': '메이크업',
  'Male Harem': '남성 하렘',
  'Male Protagonist': '남성 주인공',
  'Marriage': '결혼',
  'Martial Arts': '무술',
  'Matchmaking': '중매',
  'Matriarchy': '모계사회',
  'Medicine': '의학',
  'Memory Manipulation': '기억 조작',
  'Mermaid': '인어',
  'Meta': '메타적',
  'Metal Music': '메탈 음악',
  'Military': '군대',
  'Mixed Gender Harem': '혼성 하렘',
  'Monster Boy': '몬스터 소년',
  'Monster Girl': '몬스터 소녀',
  'Mopeds': '모페드',
  'Motorcycles': '오토바이',
  'Mountaineering': '등산',
  'Musical Theater': '뮤지컬',
  'Mythology': '신화',
  'Natural Disaster': '자연재해',
  'Necromancy': '네크로멘서',
  'Nekomimi': '고양이 귀',
  "Netorare": "네토라레",
  'Ninja': '닌자',
  'No Dialogue': '대사 없음',
  'Noir': '누아르',
  'Non-fiction': '논픽션',
  'Nudity': '누드',
  'Nun': '수녀',
  'Office': '사무실',
  'Office Lady': '오피스 레이디',
  'Oiran': '오이란',
  'Ojou-sama': '아가씨',
  'Orphan': '고아',
  'Otaku Culture': '오타쿠 문화',
  'Outdoor': '야외',
  'POV': '시점 (POV)',
  'Pandemic': '전염병',
  'Parenthood': '부모 역할',
  'Parkour': '파쿠르',
  'Parody': '패러디',
  'Philosophy': '철학',
  'Photography': '사진',
  'Pirates': '해적',
  'Poker': '포커',
  'Police': '경찰',
  'Politics': '정치',
  'Polyamorous': '폴리아모리',
  'Post-Apocalyptic': '포스트 아포칼립스',
  'Primarily Adult Cast': '주로 성인 캐스트',
  'Primarily Animal Cast': '동물 주연',
  'Primarily Child Cast': '아동 주연',
  'Primarily Female Cast': '주로 여성 캐스트',
  'Primarily Male Cast': '주로 남성 캐스트',
  'Primarily Teen Cast': '주로 청소년 캐스트',
  'Prison': '감옥',
  'Proxy Battle': '대리전',
  'Psychosexual': '정신 성욕',
  'Puppetry': '인형극',
  'Rakugo': '라쿠고',
  'Real Robot': '리얼 로봇',
  'Rehabilitation': '재활',
  'Reincarnation': '환생',
  'Religion': '종교',
  'Restaurant': '식당',
  'Revenge': '복수',
  'Robots': '로봇',
  'Rock Music': '록 음악',
  'Rotoscoping': '로토스코핑',
  'Royal Affairs': '왕실 업무',
  'Rugby': '럭비',
  'Rural': '시골',
  'Samurai': '사무라이',
  'Satire': '풍자',
  'School': '학교',
  'School Club': '학교 클럽',
  'Scuba Diving': '스쿠버 다이빙',
  'Seinen': '청년',
  'Shapeshifting': '형태 변환',
  'Ships': '배',
  'Shogi': '쇼기',
  'Shoujo': '소녀 ',
  'Shounen': '소년',
  'Shrine Maiden': '무녀',
  'Skateboarding': '스케이트보드',
  'Skeleton': '해골',
  'Slapstick': '몸개그',
  'Slavery': '노예제도',
  'Snowscape': '설경',
  'Software Development': '소프트웨어 개발',
  'Space': '우주',
  'Space Opera': '우주 여행',
  'Spearplay': '창술',
  'Steampunk': '스팀펑크',
  'Stop Motion': '스톱 모션',
  'Succubus': '서큐버스',
  'Suicide': '자살',
  'Sumo': '스모',
  'Super Power': '초능력',
  'Super Robot': '슈퍼 로봇',
  'Superhero': '슈퍼히어로',
  'Surfing': '서핑',
  'Surreal Comedy': '초현실 코미디',
  'Survival': '서바이벌',
  'Swimming': '수영',
  'Swordplay': '검술',
  'Table Tennis': '탁구',
  'Tanks': '전차',
  'Tanned Skin': '갈색 피부',
  'Teacher': '교사',
  "Teens' Love": '청소년 사랑',
  'Tennis': '테니스',
  'Terrorism': '테러',
  'Time Loop': '타임 루프',
  'Time Manipulation': '시간 조작',
  'Time Skip': '시간 도약',
  'Tokusatsu': '특촬',
  'Tomboy': '톰보이',
  'Torture': '고문',
  'Tragedy': '비극',
  'Trains': '기차',
  'Transgender': '트랜스젠더',
  'Travel': '여행',
  'Triads': '삼합회',
  'Tsundere': '츤데레',
  'Twins': '쌍둥이',
  'Unrequited Love': '짝사랑',
  'Urban': '도시',
  'Urban Fantasy': '도시 판타지',
  'VTuber': '버튜버 (VTuber)',
  'Vampire': '뱀파이어',
  'Veterinarian': '수의사',
  'Video Games': '비디오 게임',
  'Vikings': '바이킹',
  'Villainess': '악녀',
  'Virtual World': '가상 세계',
  'Volleyball': '배구',
  'War': '전쟁',
  'Werewolf': '늑대인간',
  'Witch': '마녀',
  'Work': '직장',
  "Watersports": "수상 스포츠",
  'Wrestling': '레슬링',
  'Writing': '글쓰기',
  'Wuxia': '무협',
  'Yakuza': '야쿠자',
  'Yandere': '얀데레',
  'Youkai': '요괴',
  'Yuri': '백합',
  'Zombie': '좀비'
};

// 태그를 한글로 번역하는 함수
const translateTag = (tags) => {
  const translatedTags = tags.map((tag) => tagTranslations[tag] || tag); // 매핑된 번역이 없으면 원래 이름 사용
  return translatedTags;
};

module.exports = {
  translateStaffName,
  translateStaffRole,
  translateGenre,
  translateTag,
};
